packages:
  - "apps/*"
  - "packages/*"
overrides:
  esbuild@0.18.20: "0.25.12"
  undici: "^7.29.1"
onlyBuiltDependencies:
  - sharp
  - esbuild
  - '@swc/core'
  - argon2
  - bcrypt
  - unrs-resolver
dangerouslyAllowAllBuilds: true
