/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "OrderStatus".
 */
export type OrderStatus = ('processing' | 'completed' | 'cancelled' | 'refunded') | null;
/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    pages: Page;
    media: Media;
    categories: Category;
    brands: Brand;
    'attribute-types': AttributeType;
    'attribute-values': AttributeValue;
    prices: Price;
    'discount-codes': DiscountCode;
    addresses: Address;
    variants: Variant;
    variantTypes: VariantType;
    variantOptions: VariantOption;
    products: Product;
    carts: Cart;
    orders: Order;
    transactions: Transaction;
    'component-categories': ComponentCategory;
    components: Component;
    'compatibility-rules': CompatibilityRule;
    'derived-power-rules': DerivedPowerRule;
    'build-templates': BuildTemplate;
    'configured-builds': ConfiguredBuild;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    variantTypes: {
      options: 'variantOptions';
    };
    products: {
      variants: 'variants';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    brands: BrandsSelect<false> | BrandsSelect<true>;
    'attribute-types': AttributeTypesSelect<false> | AttributeTypesSelect<true>;
    'attribute-values': AttributeValuesSelect<false> | AttributeValuesSelect<true>;
    prices: PricesSelect<false> | PricesSelect<true>;
    'discount-codes': DiscountCodesSelect<false> | DiscountCodesSelect<true>;
    addresses: AddressesSelect<false> | AddressesSelect<true>;
    variants: VariantsSelect<false> | VariantsSelect<true>;
    variantTypes: VariantTypesSelect<false> | VariantTypesSelect<true>;
    variantOptions: VariantOptionsSelect<false> | VariantOptionsSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    carts: CartsSelect<false> | CartsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    transactions: TransactionsSelect<false> | TransactionsSelect<true>;
    'component-categories': ComponentCategoriesSelect<false> | ComponentCategoriesSelect<true>;
    components: ComponentsSelect<false> | ComponentsSelect<true>;
    'compatibility-rules': CompatibilityRulesSelect<false> | CompatibilityRulesSelect<true>;
    'derived-power-rules': DerivedPowerRulesSelect<false> | DerivedPowerRulesSelect<true>;
    'build-templates': BuildTemplatesSelect<false> | BuildTemplatesSelect<true>;
    'configured-builds': ConfiguredBuildsSelect<false> | ConfiguredBuildsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
  /**
   * Generated by the Payload Ecommerce plugin
   */
  ecommerce: {
    collections: {
      addresses: Address;
      carts: Cart;
      customers?: User;
      orders: Order;
      products: Product;
      transactions: Transaction;
      variantOptions: VariantOption;
      variants: Variant;
      variantTypes: VariantType;
    };
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  roles?: ('admin' | 'manager' | 'staff' | 'customer')[] | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  /**
   * Exactly one page renders / (enforced server-side)
   */
  isHomepage?: boolean | null;
  layout?:
    | (
        | {
            heading: string;
            subheading?: string | null;
            image?: (number | null) | Media;
            /**
             * YouTube or Vimeo URL — used when variant = video
             */
            videoUrl?: string | null;
            variant?: ('image' | 'split' | 'video') | null;
            align?: ('left' | 'center') | null;
            ctas?:
              | {
                  label: string;
                  url: string;
                  style?: ('primary' | 'secondary') | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            richtext: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            heading?: string | null;
            category?: (number | null) | Category;
            limit?: number | null;
            columns?: ('2' | '3' | '4') | null;
            viewAllLabel?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'productGrid';
          }
        | {
            category: number | Category;
            image?: (number | null) | Media;
            heading: string;
            copy?: string | null;
            ctaLabel?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'featuredCategory';
          }
        | {
            heading: string;
            copy?: string | null;
            ctaLabel?: string | null;
            ctaUrl?: string | null;
            tone?: ('dark' | 'indigo' | 'slate') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'ctaBanner';
          }
        | {
            heading?: string | null;
            tagFilter?: string | null;
            autoplay?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'templatesCarousel';
          }
        | {
            heading?: string | null;
            columns: {
              label: string;
              id?: string | null;
            }[];
            rows?:
              | {
                  label: string;
                  values?:
                    | {
                        value?: string | null;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'comparisonTable';
          }
        | {
            heading?: string | null;
            items?:
              | {
                  question: string;
                  answer: {
                    root: {
                      type: string;
                      children: {
                        type: any;
                        version: number;
                        [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                    };
                    [k: string]: unknown;
                  };
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faq';
          }
        | {
            heading?: string | null;
            items?:
              | {
                  quote: string;
                  name: string;
                  role?: string | null;
                  avatar?: (number | null) | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonials';
          }
        | {
            heading?: string | null;
            brands?: (number | Brand)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'logosStrip';
          }
        | {
            heading?: string | null;
            consent?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'newsletterSignup';
          }
        | {
            provider?: ('youtube' | 'vimeo') | null;
            url: string;
            poster?: (number | null) | Media;
            title?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'videoEmbed';
          }
      )[]
    | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    gallery?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  slug: string;
  parent?: (number | null) | Category;
  image?: (number | null) | Media;
  description?: string | null;
  topBlocks?:
    | (
        | {
            heading: string;
            subheading?: string | null;
            image?: (number | null) | Media;
            /**
             * YouTube or Vimeo URL — used when variant = video
             */
            videoUrl?: string | null;
            variant?: ('image' | 'split' | 'video') | null;
            align?: ('left' | 'center') | null;
            ctas?:
              | {
                  label: string;
                  url: string;
                  style?: ('primary' | 'secondary') | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            heading: string;
            copy?: string | null;
            ctaLabel?: string | null;
            ctaUrl?: string | null;
            tone?: ('dark' | 'indigo' | 'slate') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'ctaBanner';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands".
 */
export interface Brand {
  id: number;
  name: string;
  slug: string;
  logo?: (number | null) | Media;
  url?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attribute-types".
 */
export interface AttributeType {
  id: number;
  name: string;
  /**
   * URL filter param name, e.g. "socket" → ?socket=AM5
   */
  slug: string;
  valueType: 'enum' | 'number';
  /**
   * Display unit, e.g. MHz, GB, W
   */
  unit?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attribute-values".
 */
export interface AttributeValue {
  id: number;
  attributeType: number | AttributeType;
  value: string;
  displayLabel?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "prices".
 */
export interface Price {
  id: number;
  /**
   * Minor units (cents)
   */
  amount: number;
  currency: string;
  variant?: (number | null) | Variant;
  product?: (number | null) | Product;
  validFrom?: string | null;
  validUntil?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variants".
 */
export interface Variant {
  id: number;
  /**
   * Used for administrative purposes, not shown to customers. This is populated by default.
   */
  title?: string | null;
  product: number | Product;
  options: (number | VariantOption)[];
  inventory?: number | null;
  priceInEUREnabled?: boolean | null;
  priceInEUR?: number | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  title: string;
  slug: string;
  category?: (number | null) | Category;
  brand?: (number | null) | Brand;
  gallery?: (number | Media)[] | null;
  description?: string | null;
  attributeValues?:
    | {
        attributeType: number | AttributeType;
        value: number | AttributeValue;
        id?: string | null;
      }[]
    | null;
  /**
   * Cosmetic specs; display + whitelisted filters
   */
  specsJson?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  inventory?: number | null;
  enableVariants?: boolean | null;
  variantTypes?: (number | VariantType)[] | null;
  variants?: {
    docs?: (number | Variant)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  priceInEUREnabled?: boolean | null;
  priceInEUR?: number | null;
  /**
   * Set by the PC builder plugin when a component references this product
   */
  isComponent?: boolean | null;
  /**
   * Builder component bound to this product (admin-only visibility)
   */
  component?: (number | null) | Component;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variantTypes".
 */
export interface VariantType {
  id: number;
  label: string;
  name: string;
  options?: {
    docs?: (number | VariantOption)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variantOptions".
 */
export interface VariantOption {
  id: number;
  _variantOptions_options_order?: string | null;
  variantType: number | VariantType;
  label: string;
  /**
   * should be defaulted or dynamic based on label
   */
  value: string;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "components".
 */
export interface Component {
  id: number;
  name: string;
  /**
   * Price/SKU/inventory source — A1: component references a ProductVariant
   */
  productVariant: number | Variant;
  category: number | ComponentCategory;
  brand?: (number | null) | Brand;
  images?: (number | Media)[] | null;
  description?: string | null;
  marketingCopy?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  socket?: ('AM5' | 'LGA1700' | 'LGA1851') | null;
  ramType?: ('DDR4' | 'DDR5') | null;
  ramSpeedMhz?: number | null;
  tdpWatts?: number | null;
  psuWatts?: number | null;
  moboFormFactor?: ('ATX' | 'mATX' | 'ITX') | null;
  caseSupportedFormFactors?: ('ATX' | 'mATX' | 'ITX')[] | null;
  gpuLengthMm?: number | null;
  caseGpuMaxLengthMm?: number | null;
  coolerSocketSupport?: ('AM5' | 'LGA1700' | 'LGA1851')[] | null;
  storageInterface?: ('NVMe' | 'SATA') | null;
  pcieVersion?: ('3.0' | '4.0' | '5.0') | null;
  /**
   * Cosmetic specs; display + whitelisted filters
   */
  specsJson?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  compatTags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  /**
   * OS slot special-casing
   */
  isOsLicense?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "component-categories".
 */
export interface ComponentCategory {
  id: number;
  name: string;
  slug: string;
  /**
   * Token name from packages/ui icon set
   */
  icon?: string | null;
  sortOrder?: number | null;
  required?: boolean | null;
  /**
   * e.g. storage = 2, case-fan = 6
   */
  maxSelectable?: number | null;
  helperText?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "discount-codes".
 */
export interface DiscountCode {
  id: number;
  code: string;
  type: 'percentage' | 'fixed' | 'freeShipping';
  /**
   * Percent (0-100) for percentage; cents for fixed
   */
  value?: number | null;
  maxUses?: number | null;
  usedCount?: number | null;
  /**
   * Cents; applies when cart subtotal >= this
   */
  minSubtotal?: number | null;
  validFrom?: string | null;
  validUntil?: string | null;
  enabled?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "addresses".
 */
export interface Address {
  id: number;
  customer?: (number | null) | User;
  title?: string | null;
  firstName?: string | null;
  lastName?: string | null;
  company?: string | null;
  addressLine1?: string | null;
  addressLine2?: string | null;
  city?: string | null;
  state?: string | null;
  postalCode?: string | null;
  country:
    | 'US'
    | 'GB'
    | 'CA'
    | 'AU'
    | 'AT'
    | 'BE'
    | 'BR'
    | 'BG'
    | 'CY'
    | 'CZ'
    | 'DK'
    | 'EE'
    | 'FI'
    | 'FR'
    | 'DE'
    | 'GR'
    | 'HK'
    | 'HU'
    | 'IN'
    | 'IE'
    | 'IT'
    | 'JP'
    | 'LV'
    | 'LT'
    | 'LU'
    | 'MY'
    | 'MT'
    | 'MX'
    | 'NL'
    | 'NZ'
    | 'NO'
    | 'PL'
    | 'PT'
    | 'RO'
    | 'SG'
    | 'SK'
    | 'SI'
    | 'ES'
    | 'SE'
    | 'CH';
  phone?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carts".
 */
export interface Cart {
  id: number;
  items?:
    | {
        product?: (number | null) | Product;
        variant?: (number | null) | Variant;
        quantity: number;
        lineType?: ('standard' | 'configured-build') | null;
        configuredBuild?: (number | null) | ConfiguredBuild;
        buildName?: string | null;
        subItems?:
          | {
              component?: (number | null) | Component;
              quantity?: number | null;
              name?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  secret?: string | null;
  customer?: (number | null) | User;
  purchasedAt?: string | null;
  status?: ('active' | 'purchased' | 'abandoned') | null;
  subtotal?: number | null;
  currency?: 'EUR' | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "configured-builds".
 */
export interface ConfiguredBuild {
  id: number;
  name: string;
  user?: (number | null) | User;
  shareId?: string | null;
  slots: {
    category: number | ComponentCategory;
    components?: (number | Component)[] | null;
    id?: string | null;
  }[];
  /**
   * Display-only; recomputed server-side at checkout
   */
  priceSnapshot?: number | null;
  /**
   * { errors, warnings, rulesVersion } from the rule engine at save time
   */
  validationSnapshot?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  status?: ('draft' | 'addedToCart' | 'ordered') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  items?:
    | {
        product?: (number | null) | Product;
        variant?: (number | null) | Variant;
        quantity: number;
        lineType?: ('standard' | 'configured-build') | null;
        configuredBuild?: (number | null) | ConfiguredBuild;
        buildName?: string | null;
        subItems?:
          | {
              component?: (number | null) | Component;
              quantity?: number | null;
              name?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  shippingAddress?: {
    title?: string | null;
    firstName?: string | null;
    lastName?: string | null;
    company?: string | null;
    addressLine1?: string | null;
    addressLine2?: string | null;
    city?: string | null;
    state?: string | null;
    postalCode?: string | null;
    country?: string | null;
    phone?: string | null;
  };
  customer?: (number | null) | User;
  customerEmail?: string | null;
  transactions?: (number | Transaction)[] | null;
  status?: OrderStatus;
  amount?: number | null;
  currency?: 'EUR' | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions".
 */
export interface Transaction {
  id: number;
  items?:
    | {
        product?: (number | null) | Product;
        variant?: (number | null) | Variant;
        quantity: number;
        id?: string | null;
      }[]
    | null;
  billingAddress?: {
    title?: string | null;
    firstName?: string | null;
    lastName?: string | null;
    company?: string | null;
    addressLine1?: string | null;
    addressLine2?: string | null;
    city?: string | null;
    state?: string | null;
    postalCode?: string | null;
    country?: string | null;
    phone?: string | null;
  };
  status: 'pending' | 'processing' | 'succeeded' | 'failed' | 'cancelled' | 'expired' | 'refunded';
  customer?: (number | null) | User;
  customerEmail?: string | null;
  order?: (number | null) | Order;
  cart?: (number | null) | Cart;
  amount?: number | null;
  currency?: 'EUR' | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "compatibility-rules".
 */
export interface CompatibilityRule {
  id: number;
  subjectType: 'component' | 'category';
  subjectComponent?: (number | null) | Component;
  subjectCategory?: (number | null) | ComponentCategory;
  targetType: 'component' | 'category';
  targetComponent?: (number | null) | Component;
  targetCategory?: (number | null) | ComponentCategory;
  type: 'requires' | 'excludes' | 'supports' | 'warns';
  operator: 'equals' | 'in' | 'gte' | 'lte' | 'contains';
  /**
   * Spec key inspected on the target, e.g. socket
   */
  field: string;
  /**
   * JSON-encoded for in/contains
   */
  value: string;
  severity?: ('error' | 'warning' | 'info') | null;
  bidirectional?: boolean | null;
  /**
   * Tokens: {componentA} {componentB} {socketA} — any {key} uses the failing spec value
   */
  message?: string | null;
  enabled?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "derived-power-rules".
 */
export interface DerivedPowerRule {
  id: number;
  targetCategory: number | ComponentCategory;
  /**
   * requiredWatts = sum(tdpWatts) * multiplier + baseWatts
   */
  overheadMultiplier?: number | null;
  baseWatts?: number | null;
  severity?: ('error' | 'warning') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "build-templates".
 */
export interface BuildTemplate {
  id: number;
  name: string;
  slug: string;
  description?: string | null;
  heroCopy?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  images?: (number | Media)[] | null;
  tags?: ('gaming' | 'editing' | 'workstation' | 'streaming')[] | null;
  slots?:
    | {
        category: number | ComponentCategory;
        component?: (number | null) | Component;
        id?: string | null;
      }[]
    | null;
  /**
   * Computed from slots server-side
   */
  basePrice?: number | null;
  popularity?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'brands';
        value: number | Brand;
      } | null)
    | ({
        relationTo: 'attribute-types';
        value: number | AttributeType;
      } | null)
    | ({
        relationTo: 'attribute-values';
        value: number | AttributeValue;
      } | null)
    | ({
        relationTo: 'prices';
        value: number | Price;
      } | null)
    | ({
        relationTo: 'discount-codes';
        value: number | DiscountCode;
      } | null)
    | ({
        relationTo: 'addresses';
        value: number | Address;
      } | null)
    | ({
        relationTo: 'variants';
        value: number | Variant;
      } | null)
    | ({
        relationTo: 'variantTypes';
        value: number | VariantType;
      } | null)
    | ({
        relationTo: 'variantOptions';
        value: number | VariantOption;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'carts';
        value: number | Cart;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'transactions';
        value: number | Transaction;
      } | null)
    | ({
        relationTo: 'component-categories';
        value: number | ComponentCategory;
      } | null)
    | ({
        relationTo: 'components';
        value: number | Component;
      } | null)
    | ({
        relationTo: 'compatibility-rules';
        value: number | CompatibilityRule;
      } | null)
    | ({
        relationTo: 'derived-power-rules';
        value: number | DerivedPowerRule;
      } | null)
    | ({
        relationTo: 'build-templates';
        value: number | BuildTemplate;
      } | null)
    | ({
        relationTo: 'configured-builds';
        value: number | ConfiguredBuild;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  isHomepage?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              heading?: T;
              subheading?: T;
              image?: T;
              videoUrl?: T;
              variant?: T;
              align?: T;
              ctas?:
                | T
                | {
                    label?: T;
                    url?: T;
                    style?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              richtext?: T;
              id?: T;
              blockName?: T;
            };
        productGrid?:
          | T
          | {
              heading?: T;
              category?: T;
              limit?: T;
              columns?: T;
              viewAllLabel?: T;
              id?: T;
              blockName?: T;
            };
        featuredCategory?:
          | T
          | {
              category?: T;
              image?: T;
              heading?: T;
              copy?: T;
              ctaLabel?: T;
              id?: T;
              blockName?: T;
            };
        ctaBanner?:
          | T
          | {
              heading?: T;
              copy?: T;
              ctaLabel?: T;
              ctaUrl?: T;
              tone?: T;
              id?: T;
              blockName?: T;
            };
        templatesCarousel?:
          | T
          | {
              heading?: T;
              tagFilter?: T;
              autoplay?: T;
              id?: T;
              blockName?: T;
            };
        comparisonTable?:
          | T
          | {
              heading?: T;
              columns?:
                | T
                | {
                    label?: T;
                    id?: T;
                  };
              rows?:
                | T
                | {
                    label?: T;
                    values?:
                      | T
                      | {
                          value?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        testimonials?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    quote?: T;
                    name?: T;
                    role?: T;
                    avatar?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        logosStrip?:
          | T
          | {
              heading?: T;
              brands?: T;
              id?: T;
              blockName?: T;
            };
        newsletterSignup?:
          | T
          | {
              heading?: T;
              consent?: T;
              id?: T;
              blockName?: T;
            };
        videoEmbed?:
          | T
          | {
              provider?: T;
              url?: T;
              poster?: T;
              title?: T;
              id?: T;
              blockName?: T;
            };
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        gallery?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  parent?: T;
  image?: T;
  description?: T;
  topBlocks?:
    | T
    | {
        hero?:
          | T
          | {
              heading?: T;
              subheading?: T;
              image?: T;
              videoUrl?: T;
              variant?: T;
              align?: T;
              ctas?:
                | T
                | {
                    label?: T;
                    url?: T;
                    style?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        ctaBanner?:
          | T
          | {
              heading?: T;
              copy?: T;
              ctaLabel?: T;
              ctaUrl?: T;
              tone?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands_select".
 */
export interface BrandsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  logo?: T;
  url?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attribute-types_select".
 */
export interface AttributeTypesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  valueType?: T;
  unit?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attribute-values_select".
 */
export interface AttributeValuesSelect<T extends boolean = true> {
  attributeType?: T;
  value?: T;
  displayLabel?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "prices_select".
 */
export interface PricesSelect<T extends boolean = true> {
  amount?: T;
  currency?: T;
  variant?: T;
  product?: T;
  validFrom?: T;
  validUntil?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "discount-codes_select".
 */
export interface DiscountCodesSelect<T extends boolean = true> {
  code?: T;
  type?: T;
  value?: T;
  maxUses?: T;
  usedCount?: T;
  minSubtotal?: T;
  validFrom?: T;
  validUntil?: T;
  enabled?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "addresses_select".
 */
export interface AddressesSelect<T extends boolean = true> {
  customer?: T;
  title?: T;
  firstName?: T;
  lastName?: T;
  company?: T;
  addressLine1?: T;
  addressLine2?: T;
  city?: T;
  state?: T;
  postalCode?: T;
  country?: T;
  phone?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variants_select".
 */
export interface VariantsSelect<T extends boolean = true> {
  title?: T;
  product?: T;
  options?: T;
  inventory?: T;
  priceInEUREnabled?: T;
  priceInEUR?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variantTypes_select".
 */
export interface VariantTypesSelect<T extends boolean = true> {
  label?: T;
  name?: T;
  options?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variantOptions_select".
 */
export interface VariantOptionsSelect<T extends boolean = true> {
  _variantOptions_options_order?: T;
  variantType?: T;
  label?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  brand?: T;
  gallery?: T;
  description?: T;
  attributeValues?:
    | T
    | {
        attributeType?: T;
        value?: T;
        id?: T;
      };
  specsJson?: T;
  inventory?: T;
  enableVariants?: T;
  variantTypes?: T;
  variants?: T;
  priceInEUREnabled?: T;
  priceInEUR?: T;
  isComponent?: T;
  component?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carts_select".
 */
export interface CartsSelect<T extends boolean = true> {
  items?:
    | T
    | {
        product?: T;
        variant?: T;
        quantity?: T;
        lineType?: T;
        configuredBuild?: T;
        buildName?: T;
        subItems?:
          | T
          | {
              component?: T;
              quantity?: T;
              name?: T;
              id?: T;
            };
        id?: T;
      };
  secret?: T;
  customer?: T;
  purchasedAt?: T;
  status?: T;
  subtotal?: T;
  currency?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  items?:
    | T
    | {
        product?: T;
        variant?: T;
        quantity?: T;
        lineType?: T;
        configuredBuild?: T;
        buildName?: T;
        subItems?:
          | T
          | {
              component?: T;
              quantity?: T;
              name?: T;
              id?: T;
            };
        id?: T;
      };
  shippingAddress?:
    | T
    | {
        title?: T;
        firstName?: T;
        lastName?: T;
        company?: T;
        addressLine1?: T;
        addressLine2?: T;
        city?: T;
        state?: T;
        postalCode?: T;
        country?: T;
        phone?: T;
      };
  customer?: T;
  customerEmail?: T;
  transactions?: T;
  status?: T;
  amount?: T;
  currency?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions_select".
 */
export interface TransactionsSelect<T extends boolean = true> {
  items?:
    | T
    | {
        product?: T;
        variant?: T;
        quantity?: T;
        id?: T;
      };
  billingAddress?:
    | T
    | {
        title?: T;
        firstName?: T;
        lastName?: T;
        company?: T;
        addressLine1?: T;
        addressLine2?: T;
        city?: T;
        state?: T;
        postalCode?: T;
        country?: T;
        phone?: T;
      };
  status?: T;
  customer?: T;
  customerEmail?: T;
  order?: T;
  cart?: T;
  amount?: T;
  currency?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "component-categories_select".
 */
export interface ComponentCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  icon?: T;
  sortOrder?: T;
  required?: T;
  maxSelectable?: T;
  helperText?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "components_select".
 */
export interface ComponentsSelect<T extends boolean = true> {
  name?: T;
  productVariant?: T;
  category?: T;
  brand?: T;
  images?: T;
  description?: T;
  marketingCopy?: T;
  socket?: T;
  ramType?: T;
  ramSpeedMhz?: T;
  tdpWatts?: T;
  psuWatts?: T;
  moboFormFactor?: T;
  caseSupportedFormFactors?: T;
  gpuLengthMm?: T;
  caseGpuMaxLengthMm?: T;
  coolerSocketSupport?: T;
  storageInterface?: T;
  pcieVersion?: T;
  specsJson?: T;
  compatTags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  isOsLicense?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "compatibility-rules_select".
 */
export interface CompatibilityRulesSelect<T extends boolean = true> {
  subjectType?: T;
  subjectComponent?: T;
  subjectCategory?: T;
  targetType?: T;
  targetComponent?: T;
  targetCategory?: T;
  type?: T;
  operator?: T;
  field?: T;
  value?: T;
  severity?: T;
  bidirectional?: T;
  message?: T;
  enabled?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "derived-power-rules_select".
 */
export interface DerivedPowerRulesSelect<T extends boolean = true> {
  targetCategory?: T;
  overheadMultiplier?: T;
  baseWatts?: T;
  severity?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "build-templates_select".
 */
export interface BuildTemplatesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  heroCopy?: T;
  images?: T;
  tags?: T;
  slots?:
    | T
    | {
        category?: T;
        component?: T;
        id?: T;
      };
  basePrice?: T;
  popularity?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "configured-builds_select".
 */
export interface ConfiguredBuildsSelect<T extends boolean = true> {
  name?: T;
  user?: T;
  shareId?: T;
  slots?:
    | T
    | {
        category?: T;
        components?: T;
        id?: T;
      };
  priceSnapshot?: T;
  validationSnapshot?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}